server:
  port: 8081

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: pass

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/botdb
    username: user
    password: pass
  jpa:
    generate-ddl: true